---
driver:
  name: vagrant
  synced_folders: 
    - ["/var/www/work/my/PGD/pgd_1.4/vagrant/pgd", "/home/vagrant/pgd"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: vagrant
    run_list:
      - recipe[pgd_cookbook::default]
      - recipe[pgd_cookbook::database]
    attributes: